---
kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: codeanker/drone-kaniko:0.5.2
  settings:
    repo: codeanker/drone-kaniko
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password