---
kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    repo: codeanker/drone-kaniko
    context: /drone/src
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password