---
kind: pipeline
type: kubernetes
name: default

steps:
- name: kaniko
  image: codeanker/drone-kaniko:0.5.4
  settings:
    repo: codeanker/drone-kaniko
    tags: ${DRONE_COMMIT_SHA}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password